name: Build an Android APK

on:
  push:
    paths-ignore:
      - '**/*.md'
    branches:
      - main

jobs:
  build-and-deploy:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      # Setup Java environment in order to build the Android app.
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      # Setup the flutter environment.
      - uses: subosito/flutter-action@v2

      # Get flutter dependencies.
      - run: flutter pub get

      # Statically analyze the Dart code for any errors.
      # - run: flutter analyze .

      # Run tests
      # - run: flutter test

      # Build the Android apk.
      - run: flutter build apk

      # Upload generated apk to the artifacts.
      - uses: actions/upload-artifact@v3
        with:
          name: flutter-actions-test
          path: build/app/outputs/flutter-apk/app-release.apk