name: Build an Android APK

on:
  push:
    paths:
      - '*'
      - '.github/workflows/build-apk.yml'
      - 'assets/**'
      - 'lib/**'
      - 'android/**'
      - '!**/*.md'
    branches:
      - main

jobs:
  build-apk:
    permissions:
      contents: write
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Setup Java environment in order to build the Android app.
      - name: Setup Java environment
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      # Setup gradle using official gradle action
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          add-job-summary: 'on-failure'

      # Setup the flutter environment.
      - name: Setup Flutter environment
        uses: subosito/flutter-action@v2
        with:
          cache: true

      # Get flutter dependencies.
      - name: Install Flutter dependencies
        run: flutter pub get

      # Statically analyze the Dart code for any errors.
      # - run: flutter analyze .

      # Run tests
      # - run: flutter test

      # Build the Android apk.
      - name: Build Android APK
        run: flutter build apk

      # Upload generated apk to the artifacts.
      - name: Save apk file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: flutter-samples
          path: build/app/outputs/flutter-apk/app-release.apk